### ISSUE TITLE
Add sweetalert

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#14]
when submitting the form ,if the field is not filled standard popup is coming change it to sweetalert
Refer [here](https://github.com/t4t5/sweetalert)

**Comment by namantw** [comment]
I will do it

**Comment by aswinzz** [comment]
sure

**Comment by aswinzz** [comment]
updates?

**Comment by namantw** [comment]
Which files should I be looking for? I find this a bit too tough :(

**Comment by namantw** [comment]
Found it!
PR is on its way :)
