### ISSUE TITLE
Fix logo

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#16]

**Comment by Tachyon01** [comment]
I will fix it

**Comment by aswinzz** [comment]
Okay

**Comment by aswinzz** [comment]
Okay

**Comment by aswinzz** [comment]
@Tachyon01  logo hasn't been fixed. url should be "/images/lucidcv.png"

**Comment by strikertanmay** [comment]
may i solve this issue ?

**Comment by aswinzz** [comment]
@Tachyon has already made the pr and this was a minor mistake so i cant assign it to you @strikertanmay

**Comment by hacker1x1x1** [comment]
Can I work on this issue?
