### ISSUE TITLE
Add a good background

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#18]

**Comment by aryan-harsh** [comment]
I want to work on this. 😄

**Comment by strikertanmay** [comment]
can i work on it ..?

**Comment by aswinzz** [comment]
@aryan-harsh gets it

**Comment by aswinzz** [comment]
@aryan-harsh status?

**Comment by aryan-harsh** [comment]
@aswinzz am i supposed to just add a background colour ?

**Comment by Esha23** [comment]
Can I try??

**Comment by hacker1x1x1** [comment]
Any updated @aswinzz 
Can I work on this issue?

**Comment by aswinzz** [comment]
@hacker1x1x1  you can work on it
