### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#2]
This issue is open to everyone.Make the UI more awesome.
trivial changes are not encouraged!

**Comment by Ace-Bansal** [comment]
I would like to work on this issue.

**Comment by aswinzz** [comment]
You can work on this

**Comment by aswinzz** [comment]
@Ace-Bansal  give the link of your PR here in the comments

**Comment by Ace-Bansal** [comment]
Here it is [link](https://ace-bansal.github.io/LucidCV/)

**Comment by swaager** [comment]
Is it open or closed?

**Comment by aswinzz** [comment]
its open fore everyone
improve the UI to make it look awesome
