### ISSUE TITLE
Suggest more issues

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#20]
Comment down the issues that you find and we will create new issues for that.

**Comment by hacker1x1x1** [comment]
we can add a custom scroll bar for better views!

**Comment by nikki1016** [comment]
heading of those fields which are empty should not be displayed like if i have no industrial exposure yet then experiences heading should not be visible.

**Comment by hiteshpr** [comment]
The Web App should be made responsive so that users on mobile get a good experience

**Comment by hiteshpr** [comment]
Add calendar (datepicker) to date inputs fields

**Comment by hiteshpr** [comment]
Add javascript/jquery form input validations

**Comment by hiteshpr** [comment]
Auto-suggest form inputs like institute name/ course name/ languages.

**Comment by nityanandagohain** [comment]
The is a extra card below the projects and experience card . I think it looks quite odd

![screenshot from 2018-01-17 22-29-25](https://user-images.githubusercontent.com/26831659/35056263-574af04c-fbd7-11e7-8541-b6598f79e55c.png)

**Comment by Pedrocssg** [comment]
Add a Contribution Guide file! I'll work on it if you want.

**Comment by SpaceLenore** [comment]
Twitter and Facebook should not be required, those are personal social platforms and isn't really work related. They should be available but it shouldn't be required

update the npm package mine to avoid 2 moderate severity vulnerabilities. This requires updating express to ^4.16.3
