### ISSUE TITLE
Make CV Downloadable

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#3]
As of now the user can only view the CV, make either the json file downloadable or the html code.

**Comment by aadixiiita** [comment]
I would like to work on it ..

**Comment by aswinzz** [comment]
did u set the project locally?

**Comment by aadixiiita** [comment]
Yes sir ..

**Comment by aadixiiita** [comment]
i have got another issue ..

**Comment by swaager** [comment]
I would like to work on this issue

**Comment by aswinzz** [comment]
@swaager  you can work on this

**Comment by hiteshpr** [comment]
@aswinzz  I would like to work on this

**Comment by hacker1x1x1** [comment]
can i work on this issue @aswinzz

**Comment by aswinzz** [comment]
@hiteshpr  you can work on this

**Comment by hiteshpr** [comment]
@aswinzz Please review the pull request
