### ISSUE TITLE
How to contribute markdown file

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#47]
create a how_to_contribute.md file in which steps to contribute will be added

**Comment by mohancm** [comment]
@aswinzz i am doing :)

**Comment by KeyJoo** [comment]
:+1: Good practic using `TAB Projects` like a **Trello** (Task Manager))

**Comment by aswinzz** [comment]
@mohancm  create a file how_to_contribute.md and this will contain the steps to contribute

**Comment by mohancm** [comment]
@aswinzz how_to_contribute.md already present
