### ISSUE TITLE
add steps to contribute

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#48]
Add this in the how_to_contribute.md file (once it is made)
# How To Contribute To This Repo!
## NOTE: PR's will be merged if you star the repo!!
- Star This Repo
- Fork This Repo To Your Account
- Add Yourself To The CONTRIBUTING.md file
- Create A PullRequest
    - Make sure to include the issue number and a link to a gh page for your contribution as shown in PULL_REQUEST_TEMPLATE.md
- Solve issues
- You can also create new issues which you think needs to be added in this Repo.
- Enjoy Contributing :blush:

**Comment by Pedrocssg** [comment]
#52 Should this be on a separate file or in the README.md? I think it's better to have it in README.md as it is the first thing people see when they enter the repo.

**Comment by hiteshpr** [comment]
I can work on this.

**Comment by aswinzz** [comment]
@Pedrocssg  it should be on a seperate file
