### ISSUE TITLE
Integrate newly added themes to the website

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#5]
after creating the templates. they must be added to the form and according to the selection.
For that edit index.ejs and add the theme to the theme selection option.Then in `routes->index.js` render the required theme according to the user selection.

**Comment by Tlazypanda** [comment]
I would be interested.

**Comment by aswinzz** [comment]
@Tlazypanda  you can do this. what you have to do is in the form there is an option to select theme so on the basis of the selection you have to render different themes. 
![screenshot from 2018-01-14 11-00-37](https://user-images.githubusercontent.com/25057819/34913116-41980ce0-f91a-11e7-816b-10d08f14744d.png)
add a condition based on the selected themes and render the ejs file.

**Comment by aswinzz** [comment]
Integrate the newly added theme ie theme2.ejs! anyone can takeup this issue

**Comment by hacker1x1x1** [comment]
can I work on this?

**Comment by aswinzz** [comment]
Yeah

**Comment by hacker1x1x1** [comment]
Pls unassign me this and let anybody else work on this issue!

**Comment by aswinzz** [comment]
Anyone?

**Comment by Ace-Bansal** [comment]
I'd like to give it a go

**Comment by aswinzz** [comment]
Help : What you have to do is, in the screenshot given below there is a line `res.render(theme2.ejs...)` this code renders the template theme2.ejs . 
![screenshot-2018-1-20 aswinzz lucidcv](https://user-images.githubusercontent.com/25057819/35180885-f9183318-fdde-11e7-9d33-2e2f6dedf974.png)
so to add new themes what you have to do is ,
![screenshot-2018-1-20 aswinzz lucidcv 1](https://user-images.githubusercontent.com/25057819/35180900-5143fdc4-fddf-11e7-80ac-45740c26a07c.png)
give a name for the theme selection option and get the selected theme and by adding an if else statement and place the res.render command accordingly.

**Comment by Ace-Bansal** [comment]
@aswinzz alright thank you :)

**Comment by aswinzz** [comment]
@Ace-Bansal  status?
