### ISSUE TITLE
UI doesn't show up on npm start

### ISSUE THREAD

**Issue by mkkhedawat** [aswinzz/LucidCV#54]
$ npm install
$ npm start

Browser : http://localhost:3000/

UI does not show up. throws  404s on many assets. Looks like structure is incorrect.

Is it just me ?

**Comment by aswinzz** [comment]
![screenshot from 2018-10-02 14-19-34](https://user-images.githubusercontent.com/25057819/46338594-35f81680-c64e-11e8-9290-1e81281cb8f6.png)
Its coming for me though !

**Comment by mkkhedawat** [comment]
Try fresh clone.
![lucidcv](https://user-images.githubusercontent.com/5137374/46338863-f0881900-c64e-11e8-8a13-cfdc633937a5.png)

**Comment by mkkhedawat** [comment]
Raised Pull Requst for fix : https://github.com/aswinzz/LucidCV/pull/63

**Comment by aswinzz** [comment]
Yeah fresh clone only, I didn't have the project locally .. So i cloned it and started the server. Its is working for me
