### ISSUE TITLE
Add Loader when CV is being generated

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#6]

**Comment by Ace-Bansal** [comment]
I would like to work on this.

**Comment by aswinzz** [comment]
Sure

**Comment by aswinzz** [comment]
@Ace-Bansal  any updates?

**Comment by Ace-Bansal** [comment]
Currently working on it.

**Comment by aswinzz** [comment]
@hiteshpr  you chave been assigned one issue
Anyone else can take up this issue

**Comment by falconis** [comment]
I'd like to work on this.

**Comment by aswinzz** [comment]
@falconis yeah

**Comment by aswinzz** [comment]
@falconis  status?

**Comment by falconis** [comment]
Sorry, couldn't make the app work. Pls reassign.:disappointed:

**Comment by aswinzz** [comment]
Anyone else?

**Comment by hiteshpr** [comment]
I can work on this.

**Comment by aswinzz** [comment]
@hiteshpr  Go Ahead
