### ISSUE TITLE
Setup LucidCV in your local system

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#7]
It will be easy work on other issues once you have the project locally.
everyone who like to work on this project please complete this issue. 
If you face any issue, ask them in the zulip channel

**Comment by nityanandagohain** [comment]
screen-shot will be ok?

**Comment by aswinzz** [comment]
Yeah

**Comment by nityanandagohain** [comment]
![screenshot from 2018-01-10 10-43-43](https://user-images.githubusercontent.com/26831659/34756811-591f1a4a-f5f3-11e7-9ebb-add5ac505bb5.png)
I have set it up

**Comment by aswinzz** [comment]
Cool!

**Comment by hacker1x1x1** [comment]
![cv jpeg](https://user-images.githubusercontent.com/34509429/34814067-3b4e68d6-f661-11e7-9139-f845cee06888.png)

**Comment by hacker1x1x1** [comment]
![image](https://user-images.githubusercontent.com/34509429/34814078-499a64b2-f661-11e7-8281-17cbc8687187.png)
i have opened it using xampp

**Comment by aswinzz** [comment]
Thats totally fine

**Comment by AK-007** [comment]
Used Xampp
![screenshot 50](https://user-images.githubusercontent.com/26346816/34824234-a135aa78-f6f3-11e7-918e-172cdfec8db0.png)

**Comment by namantw** [comment]
using npm on windows @aswinzz 
![image](https://user-images.githubusercontent.com/31323328/34830073-c23fcb08-f708-11e7-93be-1d8e8f9ac342.png)

**Comment by swaager** [comment]
![cv](https://user-images.githubusercontent.com/29673845/34837663-8094bfd8-f721-11e7-9cbd-a466d5ed5baf.png)

**Comment by brain-sick** [comment]
![2](https://user-images.githubusercontent.com/34164978/34840182-35c39390-f72a-11e7-8873-44f16d744756.png)

**Comment by adiagg2000** [comment]
used XAMPP

![cv](https://user-images.githubusercontent.com/33027339/34843625-f87f723c-f734-11e7-8584-2ddd6b4a7558.png)

**Comment by arshjat** [comment]
![screenshot from 2018-01-12 20-35-29](https://user-images.githubusercontent.com/29671220/34868520-181a81f2-f7aa-11e7-90ac-8fced89b0e74.png)

**Comment by hacker1x1x1** [comment]
![image](https://user-images.githubusercontent.com/34509429/34904943-5d783e88-f804-11e7-9a51-a7ddb86c86e9.png)

**Comment by hiteshpr** [comment]
![lucidcv](https://user-images.githubusercontent.com/19280178/34918858-00f09084-f980-11e7-88fb-fcdf9ce6a0fe.png)

**Comment by Ace-Bansal** [comment]
![screenshot 38](https://user-images.githubusercontent.com/34866483/34948881-68cc0c92-fa34-11e7-9b03-0586e77d5835.png)

**Comment by aswinzz** [comment]
@Ace-Bansal  finally :stuck_out_tongue_winking_eye:

**Comment by Ace-Bansal** [comment]
@aswinzz yep... finally 😂😂😂😂

**Comment by Tlazypanda** [comment]
![image](https://user-images.githubusercontent.com/33183263/35068456-1f4cea3a-fbfd-11e7-93c0-35b4e2f727a9.png)

**Comment by aayushjoglekar** [comment]
![whatsapp image 2018-02-10 at 11 30 06 pm 1](https://user-images.githubusercontent.com/28949397/36065028-cfd4c02e-0eba-11e8-9d46-9187ea9734e4.jpeg)
