### ISSUE TITLE
Change Heading and add logo

### ISSUE THREAD

**Issue by aswinzz** [aswinzz/LucidCV#9]
change the heading from CV-Maker to LucidCV and add the logo appropriately

**Comment by falconis** [comment]
I would like to work on this issue.

**Comment by aswinzz** [comment]
yeah sure

**Comment by falconis** [comment]
Here, do I have to only modify index.ejs in the views folder?

**Comment by Tachyon01** [comment]
I would like to work on this issue

**Comment by aswinzz** [comment]
@falconis  ya thats all
